name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Execute build stage
        run: ./run.sh --build
      - name: Execute test stage
        run: ./run.sh --test